### ISSUE TITLE
How do I compile static library with FREETYPE_GL_USE_VAO?

### ISSUE THREAD

**Issue by Ploppz** [rougier/freetype-gl#57]
Hi.

I'm unfamiliar to cmake, so I'm unsure how I should do this. Just `SET( FREETYPE_GL_USE_VAO )` in the make file?

Thanks.

Also, additional note / bonus quesiton:
Is there really no other documentation than [this](http://freetype-gl.googlecode.com/svn/wiki/doc/index.html)? It is not really helpful; to get started, I'm looking only at an example and the source code, which is not the most time-efficient way to learn how to use a library... The documentation also omits important details like the format string used in vertex_buffer_new(), and which directives you can actually set: I found out of this one when I had to debug my code and figured I'd have to set FREETYPE_GL_USE_VAO when looking at the source.

**Comment by adrianbroher** [comment]
> I'm unfamiliar to cmake, so I'm unsure how I should do this.

I hope this brief description gives you some insight into CMake.

CMake is not a build system, but a meta build system. CMake creates a platform specific build system  like, for example, GNU Makefiles on Linux, a Xcode project on MacOSX or a Visual Studio project on Windows. There are also other build systems supported like NMake or Eclipse. See the [cmake generator](http://www.cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html) manual for more details.

So when you build a project with CMake you first generate the platform specific build system and then execute this build system. Because you're asking about make files I assume you use them. The actual steps look like:

1. Generate build system. If you're familiar with auto-tools this step is similar to running `./configure` as it first checks if all dependencies required by the project are met and after that creates the requested build system.

```shell
$ cd <path to project source directory>
$ cmake . # for a pure command line configuration.
# If you prefer a more interactive configuration setup you can use
# `cmake -i .` for a question/answer style wizard or
# `ccmake .` for a small configuration editor.
```

2. Run the generated build system.

```shell
$ make
```

The CMake homepage provides a more in depth tutorial on how to [run CMake](http://www.cmake.org/runningcmake/) which is worth a reading.

That's the general idea on how you use CMake. But to come back to your more specific question:

> Just SET( FREETYPE_GL_USE_VAO ) in the make file?

The details depend on the build system you use, but the general idea is that you can:

1. Set the environment accordingly to include the define at configuration time. I recommend against using this option, because it may conflict with other settings the freetype-gl project needs now or in the future.

```shell
$ cd <path to freetype-gl project directory>
$ CFLAGS=-DFREETYPE_GL_USE_VAO cmake .
```

2. Configure the project properly by it's provided CMake option at configuration time. Currently the project doesn't expose any option to differentiate between building with or without VAO support, but that's easy to fix. I recommend this solution, because if there is some more complex configuration needed the freetype-gl maintainer should know best how to set up the project properly. The configuration would then look somewhat like (given the option is called `freetype-gl_USE_VAO`):

```shell
$ cd <path to freetype-gl project directory>
$ cmake -Dfreetype-gl_USE_VAO=ON .
```

3. Add a `ADD_DEFINITIONS ( -DFREETYPE_GL_USE_VAO )` into the freetype-gl root `CMakeFile` and again configure the freetype-gl project by calling `cmake .` in the project directory. This solution is probably most close to what you asked for. You would set this at CMakeLists.txt:89 right before the `SET( FREETYPE_GL_SRC freetype-gl.h`. I don't recommend this solution, because you would need to patch the freetype-gl code for that.

Beside configuring the freetype-gl project properly you also need to set the FREETYPE_GL_USE_VAO for every code where you include the `vertex-buffer.h` header. It's up to you if you do this with a `#define` or if you use a command line flat of your compiler.

I hope this helped you and if you still have problems figuring out on how to handle CMake: feel free to ask.


> Also, additional note / bonus quesiton:
> &lt;documentation related questions&gt;

This probably deserves a separate issue. There are some other problems with the documentation than just the incompleteness, like given the fact that Google wants to shut down it's code hosting or that CMake doesn't build the documentation at all.

**Comment by Ploppz** [comment]
Thank you very much!

I tried both `cmake -Dfreetype-gl_USE_VAO=ON .` and `cmake -DFREETYPE_GL_USE_VAO=ON .`, but it doesn't seem to affect my code. That is, the function `vertex_buffer_render` still messes up the VAO I have bound, while if I call `glBindVertexArray(0);` before calling `vertex_buffer_render`, it all runs fine. Expected result is that the line with `glBindVertexArray` sould not matter.
When I ran the former cmake command, at first I got this warning from cmake:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    freetype-gl_USE_VAO
```
But after `rm -r CMakeFiles`, running the command gave no warnings like that. The second cmake command gave that warning with or without removing `CmakeFiles`.
I also set the directive in the makefile of my project such that the line that compiles `main.cpp` is: `g++ -c src/main.cpp -o .obj/main.o -DFREETYPE_GL_USE_VAO -DUSE_GLFW  -std=c++11`

**Comment by Ploppz** [comment]
I saw the commit with the changed CMakeLists.txt, and cloned again. When I ran `cmake -Dfreetype-gl_USE_VAO=ON .`, I got this error:
```
-- Could NOT find AntTweakBar (missing:  ANT_TWEAK_BAR_INCLUDE_PATH ANT_TWEAK_BAR_LIBRARY) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ANT_TWEAK_BAR_INCLUDE_PATH
   used as include directory in directory /usr/local/include/ftgl/demos
```

**Comment by adrianbroher** [comment]
> I got this error

This is not related to the FREEORION_GL_USE_VAO configuration.

One of the demo projects of freetype-gl requires the AntTweakBar library and CMake is unable to find the library or headers of that library.
Do you need the demos to compile? If not set the `freetype-gl_BUILD_DEMOS` to `OFF` like

```shell
$ cmake -Dfreetype-gl_BUILD_DEMOS=OFF -Dfreetype-gl_USE_VAO=ON .
```

or install the AntTweakBar library and rerun CMake.

**Comment by Ploppz** [comment]
Thanks! Strange that I was able to run `cmake .` only some days ago without that error (seemingly).
