### ISSUE TITLE
Trying to recreate demo-font example (different context)

### ISSUE THREAD

**Issue by Ploppz** [rougier/freetype-gl#59]
Hi. I'm writing in C++ but I don't think it matters. I'm also using GLFW. [This](https://github.com/rougier/freetype-gl/blob/master/demos/font.c) is the demo that I'm looking at and copying (modified) code from. I'm trying to implement this in another small test case I made some time ago which will be explained shortly. I have freetype-gl compiled with `-DFREETYPE_GL_USE_VAO`, so that it does not ruin the creatively named `VAO` in my code.
[main.cpp](https://bpaste.net/show/f23168ca915b)
[glwrapper.h](https://bpaste.net/show/b89e317d3875), [glwrapper.cpp](https://bpaste.net/show/5c04b27f1b63) (don't pay too much attention to these)

Brief explanation of the functions in `main.cpp`:
`ortho2D` and `viewMatrix2D` just create projection and view matrices that I don't really use to render the font. (`ortho2D` is very similar to `mat4_set_orthographic`, but makes (0, 0) the center of the window, and `viewMatrix2D` just makes a view matrix that offsets coordinates).

Setting up the font starts at line `102`, and rendering of the text starts at line `152`. I have the directories `shaders` and `fonts` copied from this repository.

The [result](http://a.pomf.se/ydfvnw.png) is a triangle rotating in a relatively small circle. To make the text rendering more straight-forward, I use the same model, view and projection matrices as in the demo, with only the projection matrix slightly different, analogous to the projection matrix of the triangle itself. (I tested this matrix directly in the demo, and it worked as expected: [0, 0] is at the center of the window.) Model and view are identity matrices.

**My problem** is that the text does not get rendered at all. It appears to me like I do pretty much the same as in the demo itself but it still does not work. I would really appreciate of someone could look through my code and try to spot eventual errors!

Thanks!

**Comment by cforfang** [comment]
I suspect this is the problem:
```
   float identity[9] = {1, 0, 0, 0, 1, 0, 0, 0, 1};
   glUniformMatrix4fv(glGetUniformLocation(fontShader, "model"), 1, 0, identity);
   glUniformMatrix4fv(glGetUniformLocation(fontShader, "view"), 1, 0, identity);
```

`identity` needs to be a 4x4 matrix :)

Also, you probably won't be able to use v3f-t2f-c4f.vert/frag directly with a core profile GL-context. Either rewrite them or request a (non-forward) compatibility context instead.

**Comment by Ploppz** [comment]
Thanks! That was indeed the problem.  It also ran without changing the shaders. I'm not sure what you mean with core profile GL-context. Would you care to elaborate?

One small thing: The text seems to be cut off a bit on the bottom:
![screenshot](http://a.pomf.se/pbtggr.png)
This seems to also be the case in the `font` demo.

**Comment by cforfang** [comment]
Sure. I'm referring to this:
```
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
	glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
```
This requests a OpenGL 3.2 forward-compatible core context. You can read more about what that means e.g. on the [OpenGL wiki](https://www.opengl.org/wiki/Core_And_Compatibility_in_Contexts), but in short it means that some old/deprecated OpenGL-functionality is no longer available. As a result you can't, for example, use things like gl_FragColor in the shaders and also need to indicate you're targeting a sufficiently recent version of GLSL by having a #version-directive at the start. 

The alternative is to request a "compatibility context", which (if you get it) should still support all the deprecated stuff. This is not guaranteed to be available with a given driver, limiting portability, and means you could potentially use removed/deprecated functionality with realising.

You'll note from the function-name (`glfwWindowHint`) that these are only hints, so you might not get exactly what you asked for. If you didn't have any problems, you probably got a compatibility context despite asking for core. On my machine, I *do* get a core context and as such the shaders fail to compile because of the missing #version directive. :)

**Comment by Ploppz** [comment]
I see, thanks!
