### ISSUE TITLE
In the need of better documentation

### ISSUE THREAD

**Issue by Ploppz** [rougier/freetype-gl#60]
I was told this should be a separate issue so here goes.

Is [this](http://freetype-gl.googlecode.com/svn/wiki/doc/index.html) the only documentation there is? It is not really helpful. To get started, I'm looking only at a demo and the source code, trying to assemble something that might work, which is not the most time-efficient way to learn how to use a library... The documentation also omits important details like the format string used in vertex_buffer_new(), which I am still clueless about!
It should also include, for example, instructions on how to configure freetype-gl by setting directives.
It should include (at least some brief) tutorials to get started (take [freetype](http://www.freetype.org/freetype2/docs/tutorial/step1.html#section-1) as a good example). Documentation on each function separately is a good step but not sufficient, as it does not let you see the big picture of how these functions are supposed to work together. Now that's my opinion.

I'm just writing this in the hope that someone will do something about it and make freetype-gl more accessible.

Thanks!

**Comment by rougier** [comment]
Thanks, you're right. The documentation is far from being useful and this why there are so many demos.
I think it is a first help to know how to use the library. Also, one difficulty is that freetype-gl is not really meant to be a library since most users will have their own vec2/vec3/vec4 types (glm for example) as well as vertex buffer. These are meant to be replaced.

But anyway, we can start writing a proper documentation. Would you consider starting a draft (at least the structure) that I can refined. The easiest for me would be to use the wiki for the time being.

**Comment by Ploppz** [comment]
I don't really know a lot about the library but I guess I could always get wiser from looking at source code and demos. So yeah, I can always try to make a draft. Not sure when; I have some other things to do right now.
