### ISSUE TITLE
makefont produce error file header

### ISSUE THREAD

**Issue by zjhlogo** [rougier/freetype-gl#79]
print wide chars using char* parameters,
makefont.c:285 wprintf( L"Font filename              : %s\n", font_filename );

I don't know how to create a pull request, so just paste my solution here for reference(need C++11 support):

	std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> utf16conv;
	std::u16string wfont_filename = utf16conv.from_bytes(font_filename);
	std::u16string wheader_filename = utf16conv.from_bytes(header_filename);
	std::u16string wvariable_name = utf16conv.from_bytes(variable_name);

	wprintf( L"Font filename              : %s\n", wfont_filename.data());
	wprintf( L"Header filename            : %s\n", wheader_filename.data() );
	wprintf( L"Variable name              : %s\n", wvariable_name.data() );

**Comment by rougier** [comment]
Thanks for the report. Unfortunately we are trying to stick to C only.
What is the exact error you get when running the example ?

**Comment by zjhlogo** [comment]
the generated variable name became this:

texture_font_t ???????????C?C = {

![screenshoot](https://cloud.githubusercontent.com/assets/741718/9685102/9f5ee14c-534e-11e5-9510-ebee7cb6f83d.jpg)

**Comment by adrianbroher** [comment]
I think this issue is invalid now because we use `printf` functions instead of the wide counterpart to print a given char string. It seems like Microsoft swaps the meaning of the `%s` modifier and it's wide char counterpart `%S` whether it's used with `printf` or `wprintf`. This is mentioned in the [documentation] (https://msdn.microsoft.com/en-us/library/hf4y5e3w.aspx) and probably causes the error you see here.
