### ISSUE TITLE
Change copyright notice

### ISSUE THREAD

**Issue by rougier** [rougier/freetype-gl#90]
Current notice in most files reads

```
 * Copyright 2011,2012 Nicolas P. Rougier. All rights reserved.
```

It should now be something like

```
 * Copyright 2011, 2012, Nicolas P. Rougier. All rights reserved.
 * Copyright 2013, 2014, 2015 Marcel Metz & Nicolas P. Rougier. All rights reserved.
```

**Comment by adrianbroher** [comment]
Can we instead shorten the license banner inside source files to a reasonable size like Kitware did in CMake for example?  See

https://github.com/Kitware/CMake/commit/86578eccf2e82286248796bad1032cd0e3a5e1e2

**Comment by rougier** [comment]
Yes !

**Comment by adrianbroher** [comment]
@rougier

Can you please check if the changes are sufficient?  I didn't change `demos/shader.c` because I'm not sure why the license header differs from all other occurances.  Can you give an explanation why this is the case?  Also I didn't change the `edtaa3func.h` and `edtaa3func.c` license headers, because those files were not created by this project.

https://github.com/rougier/freetype-gl/compare/copyright-update

**Comment by rougier** [comment]
The `shader.c` file comes from another project (gl-agg, also from me) so we can change the license as well. For the `edtaa3func.c` and `edtaa3func.h`, yes, we need to leave the headers unchanged.

**Comment by rougier** [comment]
Changes looks good to me.
